### ISSUE TITLE
read_workbook()

### ISSUE THREAD

**Issue by GShotwell** [hadley/readxl#10]
Awesome package!

Have you thought of a read_workbook() that would bring in an entire workbook as a list of data.frames? The use case would basically be doing exploratory work on a workbook which you haven't seen before when you don't want to open the workbook itself. Sometimes those big gnarly excel sheets can be very slow to open or will crash on opening. It might be nice to be able to flip through sheets in R even when you didn't know which sheet you were looking for.

**Comment by hadley** [comment]
There's an internal `xlsx_sheets()` function that lists the sheet names. Would you want more than that + `lapply()`?

**Comment by GShotwell** [comment]
As, I didn't know about that function. For myself today I think `xlsx_sheets()` and `lapply()` work great,  but when I was first coming to R after doing a lot of Excel work, I was pretty scared of the apply family of functions, so it wouldn't have worked well. I guess I was mostly thinking of a convenience function for new R users. I bet there's a set of people who would appreciate reading in a whole workbook with a one-liner. 

Also it helps with the realization that
