### ISSUE TITLE
readxl skip and column designation not working if there are blanks

### ISSUE THREAD

**Issue by AmyMikhail** [hadley/readxl#101]
I have an MS excel sheet containing around 16,000 rows and 16 columns.  There is some un-needed text above the column  headers, so I need to skip the first three rows when reading the data in (4th row contains column headers, 5th row is the start of the data).

However I noticed that using skip=3 resulted in the column headers not being read in and everything started on the 5th row.

Also, the 2nd and 3rd column of my data contain text (names) but in one file the first 1500 cells in these columns are blank because the names are missing.  These columns are misidentified as numeric unless I specify col_types.  The 4th and subsequent columns contain data for all rows.  I tried adding an initial column with the sequence number but the result was the same.

I think both behaviors are due to the missing data; not sure if it would be possible to correct this by going to the first cell that has data in it for each column and then determining the column type from there and below (I guess if the data is mixed numeric and text, the column type would default to text and in order to do this multiple cells would have to be evaluated?)

If the automated column type assignation would work even when there is some missing data, this would be helpful as although not too much of a problem to manually specify the types for 16 columns, I often have many more than this.

Would be great if there was a fix for this - otherwise the package works great and I found it much faster than the java based ones.

**Comment by DavoOZ** [comment]
I have experienced a similar glitch.
If skip>0 and one or more of those header rows is empty, then the read starts at the wrong row.
For example, if skip=9 but there are two empty rows among those 9, then the read starts two rows further down the data than intended.
In other words, as long as some text is present somewhere in every skipped row, then the read will be fine.

**Comment by jennybc** [comment]
Concrete examples of the above would be helpful to work against.

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Preferably stripped down to the minimal size and complexity to demonstrate your point. And, obviously, stripped of any sensitive data.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained. *Currently GitHub-only, but going to CRAN soon.*
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide the xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by jennybc** [comment]
Will be fixed by #240. And the interaction with column names is covered by #157.
