### ISSUE TITLE
example file where read_excel fails but other R packages succeed

### ISSUE THREAD

**Issue by ajdamico** [hadley/readxl#107]
tf <- tempfile()

	download.file ( "http://www.huduser.org/portal/datasets/usps/ZIP_CBSA_032015.xls" , tf , mode = 'wb' )

	gdata_try <- gdata::read.xls( tf , 1 )
	# works - fast

	xlsx_try <- xlsx::read.xlsx( tf , 1 , endRow = 10 )
	# works - slowly

	readxl_try <- readxl::read_excel( tf , 1 )
	# Error: Unknown format .

**Comment by MichaelChirico** [comment]
that file appears to have been deleted. Any other reproducible examples?

**Comment by ajdamico** [comment]
here you go- it looks like the issue is in the extension?

	tf <- tempfile()

	download.file ( "http://www.huduser.org/portal/datasets/usps/ZIP_CBSA_032015.xlsx" , tf , mode = 'wb' )

	readxl_try <- readxl::read_excel( tf , 1 )
	# Error: Unknown format .

	# how to fix the problem.
	file.rename( tf , paste0( tf , ".xlsx" ) )

	# works now..  is this behavior desired?
	# the error message could at least clarify that the extension *must* be xls or xlsx
	# or the function won't even attempt to import it?
	readxl_try <- readxl::read_excel( paste0( tf , ".xlsx" ) , 1 )

**Comment by MichaelChirico** [comment]
Hmm. `readxl::read_excel("~/Desktop/ZIP_CBSA_032015.xlsx")` worked perfectly fine for me.

**Comment by hadley** [comment]
Yeah, it's because you're not giving it an extension, so this is a duplicate of #85

**Comment by ajdamico** [comment]
definitely a duplicate.  thanks!
