### ISSUE TITLE
Feature request: "skip" to accept vector

### ISSUE THREAD

**Issue by smasuda** [hadley/readxl#108]
It would be nice if we can specify skip by vector - for example, "skip=c(1,3,4)" to mean to skip #1, #3, and #4 row.

Some excels use multiple rows to specify column headers(e.g. first row to show major group, 2nd row to show sub group,  etc), and they are not ordered in such a way that the last row is interested. If an excel uses 4 rows to mean column headers, yet you want to use 2nd row to be column name, then we need "skip" to work with vector.

**Comment by hadley** [comment]
I think it's easiest to handle files like that in two steps - in step one, skip all the header rows. In step two, read just the header row you're interested in.

**Comment by b1azk0** [comment]
Any chance to consider this as a feature?

**Comment by jennybc** [comment]
Now that I know the internals here, I share @hadley's view re: the best workaround. The implementation of this would not be simple and not worth the added complexity, given readxl's focus on simple rectangles. Either work in two passes or consider packages aimed at such things, e.g. [tidyxl](https://nacnudus.github.io/tidyxl/) and [unpivotr](https://github.com/nacnudus/unpivotr).

readxl will do a better job with merged cells in the next release, which would still help https://github.com/tidyverse/readxl/issues/355
