### ISSUE TITLE
Write to .xlsx

### ISSUE THREAD

**Issue by leeper** [hadley/readxl#11]
We are currently using [openxlsx](https://github.com/awalker89/openxlsx) in [rio](https://github.com/leeper/rio). It offers read/write to .xlsx. [We'd like to incorporate reading from .xls (and thus import readxl)](https://github.com/leeper/rio/issues/19), but we don't want to lose write to .xlsx support. Any chance you can add write to .xlsx (ala what is available in openxlsx)? I don't think it make sense for us to import two different Excel-related packages.

**Comment by hadley** [comment]
Write is a pretty big job, so I'm not planning on it at the moment.
