### ISSUE TITLE
Column type is determined by first 100 rows.  Please document.

### ISSUE THREAD

**Issue by kwstat** [hadley/readxl#112]
In this file: https://github.com/hadley/readxl/blob/master/src/XlsxWorkSheet.h

Is this line of code:
```
std::vector<CellType> colTypes(const std::string& na, int nskip = 0, int n_max = 100, bool has_col_names = false) {
```
That appears to use the first 100 lines of data to determine the column type.  Please document this in the appropriate Rd file.  (At least, I didn't see it).  The reprex below shows what can happen if there are 100 blanks followed by data values.

```
library(openxlsx)
library(readxl)

maxrow=100
examp <- data.frame(a=1:maxrow, b=c(rep(NA,maxrow-1), "R1"))
openxlsx::write.xlsx(examp, file = "examp_100.xlsx")
read_excel("examp_100.xlsx")

maxrow=101
examp <- data.frame(a=1:maxrow, b=c(rep(NA,maxrow-1), "R1"))
openxlsx::write.xlsx(examp, file = "examp_101.xlsx")
read_excel("examp_101.xlsx")
```
The second example gives the following warning and does not read the "R1" value in row 101
```
[rows 1:98 omitted]
99   99 NA
100 100 NA
101 101 NA
Warning message:
In read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  :
  [102, 2]: expecting numeric: got 'R1'
```

**Comment by jbeaulie** [comment]
This has caused me some grief.  I have a file with >200,000 rows.  The first ~190,00, rows are blank, but the remaining are populated with text.  read_excel reads the entire column as NA.

**Comment by tklebel** [comment]
Some discussion happened in #131, I think we could close this issue here.

There is an open pull request to read 1000 rows by default. #143 

I forked `readxl` and implemented a parameter to choose the number of rows to guess the `col_type`. There is an open PR for that too #138, but it will probably take some time until Hadley works on `readxl` again.

@jbeaulie, until then you could try out the forked version:

```R
devtools::install_github("tklebel/readxl")
read_excel("file.xlsx", n = 200)
```

**Comment by kwstat** [comment]
The self-contained example at the top of this thread might still be useful.

Issues #131, #138, #143 go beyond my original request to modify the documentation and propose changes to allow more rows to determine the data type for a column.  I'll close this issue.
