### ISSUE TITLE
Feature request: Allow recycling of col_type

### ISSUE THREAD

**Issue by rickdonnelly** [hadley/readxl#114]
I tried to set a single value for col_type to text for an Excel sheet with multiple columns. I got this error message:

Error: Need one name and type for each column

Since there is no way to extract the number of columns before reading the file it would be great if col_type could recycle its arguments when the list is shorter than the number of columns, as read.table, read_table, and fread all do.

**Comment by theRanalyst** [comment]
@rickdonnelly There is actually a way to extract the number of columns in an Excel sheet before reading it in. While I agree that it would be nice to have a recycling feature, this is the workaround I've been using:
```
library(tools)
format <- file_ext(file)
functionName <- paste("readxl", format, "sheets", sep="_")
sheetNames <- .Call(functionName, PACKAGE="readxl", file)
sheetIndex <- which(sheetNames == sheet)
functionName <- paste("readxl", format, "col_names", sep="_")
n <- .Call(functionName, PACKAGE = 'readxl', file, sheetIndex, skip) %>% length()
colTypes <- rep("text", n)
dat <- read_excel(file, col_types=colTypes, sheet=sheet, skip=skip)
```
You can obviously replace "text" in the `colTypes` assignment with one of the other values that is accepted by `read_excel`.

Hope this helps!

**Comment by vergilcw** [comment]
readxl/R/RcppExports.R contains a number of helper functions that are not exported. Some of these could be useful for reading in excel sheets with unknown characteristics ahead of time (e.g. for linux users with no access to excel):
`xls_col_names` and `xlsx_col_names` as @theRanalyst suggests in his workaround
but there are also:
`xls_col_types` and `xlsx_col_types` which I assume predict the column types of a worksheet
`xlsx_dim` for getting the dimesions of the tabular data
`countRows`
and a few others.  @hadley, is there a plan to export any of these helper functions in the future?

**Comment by jennybc** [comment]
Covered by #198
