### ISSUE TITLE
Error reading sheet if position is after a chart

### ISSUE THREAD

**Issue by edwardlennonjr** [hadley/readxl#116]
Hello,
read_excel fails to read a given "sheet" worksheet if its position in the workbook is after a "chart" worksheet.

Here is a link to the example file;
https://drive.google.com/open?id=0B4_ubpPkreXXY0RMeC00RlM4a0E

The example excel file (.xlsx) contains 3 worksheets;
1) Sheet1
2) Chart1
3) Sheet2 - exact copy of Sheet1
Sheet1 imports great but Sheet2 gives the error below.  I have tested on a few different Excel files and the sheet position appears to be the issue. 

e.g. output 
read_excel(path = example_excel_file, sheet = "Sheet1")
  a  b     c
1 1 10 hello
2 2 20 there
3 3 30 world

> read_excel(path = example_excel_file, sheet = "Sheet2")
> Error: Couldn't find 'xl/worksheets/sheet3.xml' in

Issue location:
It looks like this issue can be traced to the standardise_sheet() function in the read_xlsx() function.

1) when sheet = "Sheet1" (read_excel()), standardise_sheet() computes 0 and imports fine.

2) when sheet = "Sheet2", standardise_sheet() computes 2 and the import fails.  If I manually change the result of standardise_sheet() to 1 then the import works.  

standardise_sheet() needs to remove the chart objects from "sheet_names" before evaluating the match() function.

 Thank you!

**Comment by jennybc** [comment]
Related to #104
