### ISSUE TITLE
should the col_types= parameter accept vector recycling?

### ISSUE THREAD

**Issue by ajdamico** [hadley/readxl#127]
``` r
library(readxl)

datasets <- system.file("extdata/datasets.xlsx", package = "readxl")
# read in mtcars

read_excel(datasets, "mtcars")
# read in the entire spreadsheet as text

read_excel(datasets, "mtcars",col_types=rep("text",11))
# fails because "text" does not recycle

read_excel(datasets, "mtcars",col_types="text")
```

**Comment by hadley** [comment]
No, but there will be some way. Will follow same principle as readr.

**Comment by bhive01** [comment]
Like this I presume:
https://github.com/hadley/readr/issues/148

`col_types = cols(.default = "c")`

**Comment by ReportMort** [comment]
@agogomei01 Not sure if you figured this out, but `cols` is a readr function. So before using it you must load the library or pull from the package namespace like this `readr::cols`.

**Comment by jennybc** [comment]
Covered by #198
