### ISSUE TITLE
Bug: read_excel fails to read dates

### ISSUE THREAD

**Issue by MichaelChirico** [hadley/readxl#134]
`read_excel` has failed to read dates on a simple excel file.

[Here](https://drive.google.com/file/d/0B1i6iIc4UbO1enJvZ3l5Z0o2Sm8/view?usp=sharing) is a Google Drive link to a reproducible example.

Here is the code I run on that file:

```
read_excel("test.xlsx", sheet = 1, col_names = TRUE,
           col_types = c("text", "date", "date", "date"), na = "-")
```

With warnings:

> Warning messages:
> 1: In `read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  ...`:
>   [2, 2]: expecting date: got '42369'

And so on. Here is the output `data.frame`:

```
   ID EARLIEST YEAR OWED LATEST YEAR OWED EARLIEST PAYMENT
1   A               <NA>             <NA>             <NA>
2   B               <NA>             <NA>             <NA>
3   C               <NA>             <NA>             <NA>
4   D               <NA>             <NA>             <NA>
5   E               <NA>             <NA>             <NA>
6   F               <NA>             <NA>             <NA>
7   G               <NA>             <NA>             <NA>
8   H               <NA>             <NA>             <NA>
9   I               <NA>             <NA>             <NA>
10  J               <NA>             <NA>             <NA>
```

(i.e., `read_excel` has failed miserably).

`xlsx::read.xlsx2` works perfectly fine:

```
library(xlsx)
read.xlsx2("~/Desktop/test.xlsx",sheetIndex=1,
           colClasses=c("character","Date","Date","Date"))

   ID EARLIEST.YEAR.OWED LATEST.YEAR.OWED EARLIEST.PAYMENT
1   A         2015-12-31       2015-12-31       2015-07-15
2   B         2015-12-31       2015-12-31             <NA>
3   C         2015-12-31       2015-12-31             <NA>
4   D         2015-12-31       2015-12-31             <NA>
5   E         2015-12-31       2015-12-31             <NA>
6   F         2015-12-31       2015-12-31             <NA>
7   G         2015-12-31       2015-12-31             <NA>
8   H         2015-12-31       2015-12-31             <NA>
9   I         2015-12-31       2015-12-31             <NA>
10  J               <NA>             <NA>       2015-06-25
```

Here is my session info in case it's platform-specific:

```
R version 3.2.2 (2015-08-14)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 14.04.3 LTS

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] readxl_0.1.0

loaded via a namespace (and not attached):
[1] tools_3.2.2 Rcpp_0.12.1
```

**Comment by shrektan** [comment]
You would get the right data if you change the format of the date column to `Date`, in Excel.

But I think `xlsx::read.xlsx2` has a better behavior that is having more respect on `col_types` settings.

**Comment by MichaelChirico** [comment]
I prefer not to do anything to my raw Excel files, otherwise I'd just save it as a .csv of course :)

**Comment by shrektan** [comment]
@MichaelChirico Yes, I have to agree with you. +1

**Comment by MichaelChirico** [comment]
OK, so here's as far as I've gotten with this.

It may have to do with [`cacheDateStyles`](https://github.com/hadley/readxl/blob/master/src/XlsxWorkBook.h#L105) in the [`XlsxWorkBook`](https://github.com/hadley/readxl/blob/master/src/XlsxWorkBook.h) class definition.

I note that in the file above that doesn't work, I have the following under the `numFmts` tag in `xl/styles.xml`:

```
<numFmts count="3">
    <numFmt numFmtId="164" formatCode="GENERAL"/>
    <numFmt numFmtId="165" formatCode="\$#,##0"/>
    <numFmt numFmtId="166" formatCode="M/D/YYYY"/>
</numFmts>
```

I compare this to the same `.xml` file for an `.xlsx` file for which `read_excel` detects the date successfully:

```
<numFmts count="3">
    <numFmt numFmtId="43" formatCode="_(* #,##0.00_);_(* \(#,##0.00\);_(* &quot;-&quot;??_);_(@_)"/>
    <numFmt numFmtId="166" formatCode="&quot;$&quot;#,##0"/>
    <numFmt numFmtId="168" formatCode="_(* #,##0_);_(* \(#,##0\);_(* &quot;-&quot;??_);_(@_)"/></numFmts>
```

They're clearly quite different; I've personally no idea how to parse the latter, and it seems from the [`isDateFormat`](https://github.com/hadley/readxl/blob/master/src/CellType.h#L96) code that indeed the former should have been detected as a date.

(I believe that `cacheDateStyles` is essential for the `type` method for `XlsxCell` objects to detect a date; if this returns a string, [we get the warning described above](https://github.com/hadley/readxl/blob/master/src/XlsxWorkSheet.h#L175))

**Comment by richardsc** [comment]
I'm having this same issue with the current CRAN version of `readxl`. I can provide a sample file if necessary, but it's not public so I'd rather not put it in the cloud. Can confirm that the column is set to `Date` in the xlsx file, but I'm getting the following:

```
> str(log)
Classes 'tbl_df', 'tbl' and 'data.frame':	69 obs. of  20 variables:
 $ Cast                : num  1 2 3 4 5 6 7 8 9 10 ...
 $ Glacier             : chr  NA NA "Verhoeff" "Verhoeff" ...
 $ ID                  : chr  "B" "B0" "V4" "V3" ...
 $ Date                : num  42224 42224 42225 42225 42225 ...
```

**Comment by shrektan** [comment]
Please try the Devon version I think it's improved a lot. 

发自我的 iPhone

**Comment by f34739** [comment]
Any progress on this? The most recent dev version still displays the exact same buggy behavior.

**Comment by jhn316** [comment]
Still unresolved, I am switching to xlsx::read.xlsx2.

**Comment by MichaelChirico** [comment]
@richardsc can you paste the `numFmts` field in the unzipped version of your file? See my post above. This could help establish a common thread.

**Comment by MichaelChirico** [comment]
Also for the record, the comment in `CellType.h` should note the specific edition / part to which the URL is referring. Currently there are about 20 different possibilities at the [URL noted](http://www.ecma-international.org/publications/standards/Ecma-376.htm), and the first I tried got me to the incorrect part of the pdf.

**Comment by MichaelChirico** [comment]
@richardsc @f34739 @jhn316 I believe I may have found the source of the issue.

Could any of you try reading your troublesome file with [my patch](https://github.com/MichaelChirico/readxl/tree/date_fmts) and report whether it worked?

Should be able to install with:

    devtools::install_github("MichaelChirico/readxl@date_fmts")

**Comment by ngnikhilgoyal** [comment]
@MichaelChirico don't specify the col type for the date column. Let readxl read it as an integer. Then  just try: 

```
as.Date(df$Date, origin = "1899-12-30")
```

**Comment by MichaelChirico** [comment]
@ngnikhilgoyal yes, that is the workaround, but it's not a fix.

`origin` dates may be hard to determine automatically -- it should be `readxl`'s job to do that for the user

**Comment by jennybc** [comment]
@MichaelChirico does the current development version read the file in question correctly now? This issue has been closed because a PR that (claimed to) fix this was merged. If not, we'll re-open it.

**Comment by MichaelChirico** [comment]
Yes, it does, thanks for checking! Sorry for the confusion.

**Comment by N1h1l1sT** [comment]
I'm having the same problem. readxl version ‘1.1.0’.
I get an integer returned (instead of the date that I should), and a warning:
> 50: In read_fun(path = path, sheet_i = sheet, limits = limits,  ... :
> Expecting numeric in CS1 / R1C97: got a date

_I can provide a snippet to demonstrate it if you want me to, but since this is the exact same problem as described on this thread, my initial thought is it's redundant._

**Comment by aakhmetz** [comment]
> @N1h1l1sT yes since this has been closed for 1.5 years, it would be better to open a new issue with a reproducible example

@jennybc, sorry, and what is the reference for the newly opened issue?

**Comment by jennybc** [comment]
I have no idea, we'd need to search and see if it ever showed up.

**Comment by N1h1l1sT** [comment]
> I have no idea, we'd need to search and see if it ever showed up.

No need to search. I actually never opened a new issue. I tackled the problem in R and continued on.
