### ISSUE TITLE
Erreur : Names and types must be same size

### ISSUE THREAD

**Issue by MatthieuBizien** [hadley/readxl#14]
Related to https://github.com/hadley/readxl/issues/9

Now I get other errors:

Sheet 1
```
> df = read_excel("data-science-at-the-command-line/book/ch03/data/imdb-250.xlsx", sheet=1)
Erreur : Names and types must be same size
```

**Comment by hadley** [comment]
Fixed now, by relying on excel's definition of the total range of the data. (It's a bit worrying that this doesn't actually seem to line up with the data in the rows/cells, but it seems to be mostly empty data outside the range so maybe it's ok)
