### ISSUE TITLE
Feature Request: `nrows` option

### ISSUE THREAD

**Issue by MichaelChirico** [hadley/readxl#147]
This is sort of alluded to (and would perhaps subsume?) #54.

I've got an .xlsx file where the last row is simply column totals & includes a text field reading `"Totals:"` (not all columns are totalled).

Unfortunately this is stored below a `numeric` column, so it messes up type casting for that column.

The workaround (on my branch, at least until #13 is fixed & merged) is to add `"Totals:"` to the list of `na` strings, but I think the better solution is to allow the user to specify how many rows are to be read in using `nrows`.

This is already available in `read.csv` and `data.table::fread`, for example. Seems a natural extension.

**Comment by tklebel** [comment]
I think after #8 is implemented this won't be necessary.

**Comment by jennybc** [comment]
Yes, covered by #8.
