### ISSUE TITLE
Feature request: option to fall-back to character instead of creating NAs (for "weird" text in a numeric/date column)

### ISSUE THREAD

**Issue by talgalili** [hadley/readxl#153]
Currently, when using read_excel, if I have a column of numbers with some characters (say "one"), the function would turn that cell into NA and will issue a warning.

I would benefit from a parameter ("fallback_text" or something like that) that if it detects the creation of NAs, it would instead just turn the entire column into a character vector (with a proper warning). This would allow the user to later fix the problem within R (instead of in excel).

Thanks,
Tal

**Comment by jennybc** [comment]
I think you should explicitly specify character for such a column and, as you say, fix the problem in R. That would be the safest.

If this occurs early enough in the sheet, readxl will already turn such a column into character. So, in your case, it must happen after row 100, the current number of rows consulted for column type guessing. That being said, I expect readxl might gain a `guess_max` argument, like readr has, which would give you more options.
