### ISSUE TITLE
Importing Vietnamese characters shows in console but not in Rstudio data view

### ISSUE THREAD

**Issue by Zagamog** [hadley/readxl#155]
When I import a file with Vietnamese characters, the characters display correctly in the console, but if I try to see in the Rstudio data view, the character coding shows without resolution - as in 
PH<U+1EAO>M instead of PHẠM 
NGUY<U+1C4>N instead of NGUYỄN 
Not sure if this is a readxl or RStudio issue. 
Thanks Hadley.

**Comment by jennybc** [comment]
I think this is an RStudio issue.

@kevinushey

**Comment by kevinushey** [comment]
Yes, definitely an RStudio issue. @Zagamog, if you're still seeing this issue with the latest release of RStudio, can you file an issue at http://support.rstudio.com?
