### ISSUE TITLE
Empty rows are placed at the bottom of the data frame

### ISSUE THREAD

**Issue by huftis** [hadley/readxl#156]
When importing Excel files, empty rows seem to be placed at the bottom of the resulting data frame. Here’s an example file:

http://huftis.org/nedlasting/excel/row-col-test.xlsx

The file contains two similar worksheets/tabs. Both have 8 columns (named A–H) and 8 rows. The diagonal is filled with the numbers 1 to 8 for the first worksheet. The second worksheet is similar, but is missing the number 4 and 7, resulting in row 5 and 8 being empty.

Reading the first worksheet works fine:

```
> read_excel("row-col-test.xlsx", sheet=1)
   A  B  C  D  E  F  G  H
1  1 NA NA NA NA NA NA NA
2 NA  2 NA NA NA NA NA NA
3 NA NA  3 NA NA NA NA NA
4 NA NA NA  4 NA NA NA NA
5 NA NA NA NA  5 NA NA NA
6 NA NA NA NA NA  6 NA NA
7 NA NA NA NA NA NA  7 NA
8 NA NA NA NA NA NA NA  8
```

But reading the second worksheet results in the empty rows being removed and two new empty rows placed at the bottom:

```
> read_excel("row-col-test.xlsx", sheet=2)
   A  B  C  D  E  F  G  H
1  1 NA NA NA NA NA NA NA
2 NA  2 NA NA NA NA NA NA
3 NA NA  3 NA NA NA NA NA
4 NA NA NA NA  5 NA NA NA
5 NA NA NA NA NA  6 NA NA
6 NA NA NA NA NA NA NA  8
7 NA NA NA NA NA NA NA NA
8 NA NA NA NA NA NA NA NA
```

Expected results:

```
> read_excel("row-col-test.xlsx", sheet=1)
   A  B  C  D  E  F  G  H
1  1 NA NA NA NA NA NA NA
2 NA  2 NA NA NA NA NA NA
3 NA NA  3 NA NA NA NA NA
4 NA NA NA NA NA NA NA NA
5 NA NA NA NA  5 NA NA NA
6 NA NA NA NA NA  6 NA NA
7 NA NA NA NA NA NA NA NA
8 NA NA NA NA NA NA NA  8
```

**Comment by Nihasa** [comment]
I'm having this issue as well using data generated from a machines software (tecan machine, maggelan software). It seems for some of my data this happens, and it seems to be because something is written in the cells; opening the file and pasting another empty row into the empty rows stops the rows from being placed at the bottom, but it took a while to figure out that there was a problem in the first place.

**Comment by jennybc** [comment]
I've replicated what @huftis reports, with the provided example sheet (thanks!). Now covered by #224.
