### ISSUE TITLE
Recognizing file type when downloaded from google.

### ISSUE THREAD

**Issue by jnpaulson** [hadley/readxl#158]
I'm attempting to download a simple google excel spreadsheet, but `read_excel` is not recognizing it and producing this message: [Not an excel file](https://github.com/hadley/readxl/blob/7c7f66b29764eee91385c9f1fc755b1ac6c10e08/src/ole.c#L301)

``` r
library(downloader)
library(readxl)

leFile = "http://spreadsheets.google.com/pub?key=phAwcNAVuyj2tPLxKvvnNPA&output=xls"
tmp = tempfile(fileext=".xls")
download(leFile,destfile=tmp)
le = read_excel(tmp)
```

The resulting tempfile though can be opened by excel.

**Comment by audiolion** [comment]
@jnpaulson even though readxl can read in excel files, it doesn't mean it can read in every file that MS Excel can open. I don't think readxl supports google sheets at this time. I'd recommend checking out [this link](http://stackoverflow.com/questions/22873602/importing-data-into-r-from-google-spreadsheet) and using the package listed to read in and work with google sheets

**Comment by jennybc** [comment]
If I try to open the tempfile with extension `.xls`, as described above, Excel complains about file format and file extension being mismatched.

The above works for me if I change the extension of the downloaded file: `fileext = .xlsx`.
