### ISSUE TITLE
Read and write methods that can handle horizontal (row-based) instead of vertical (column-based) data orientation

### ISSUE THREAD

**Issue by rappster** [hadley/readxl#161]
Would it be possible to introduce read and write methods that can handle Excel data stored in a **horizontal** (row-based) instead of a **vertical** (column-based) orientation (i.e. variables are represented by rows instead of columns) _while preserving the data type/class information_ of the respective variables (i.e. _not_ using coercion to `character` as a "workaround")?

Here's a little example file for both orientations: https://github.com/rappster/stackoverflow/blob/master/excel/row-and-column-based-data.xlsx
- Reading: data would need to be rearranged into a _column-based_ format so it can be stored as a `data.frame`
- Writing: data needs to be rearranged into a _row-based_ format so it complies with the original data orientation

I've elaborated a bit on the motivation for this request in a [stackoverflow post](http://stackoverflow.com/questions/35224338/transposing-a-data-frame-while-preserving-class-data-type-information?noredirect=1#comment58169113_35224338)

While a convincing reason for working against the column-based data orientation standard still escapes me, it seems like a number of platforms/tools in the area of time series analysis/business forecasting are using such a row-based/wide data orientation and I'm going mad trying to deal with it. 

A consideration of this would be greatly appreciated :-)

**Comment by rappster** [comment]
Someone at SO pointed me to `type.convert` and this seems to do the trick!

```
library(xlsx)
read.transposed.xlsx <- function(file, sheet = 1) {
  df <- xlsx::read.xlsx(file, sheetIndex = sheet , header = F)
  dft = as.data.frame(t(df[-1]), stringsAsFactors = FALSE)
  names(dft) = df[, 1]
  # dft <- lapply(dft, as.character)
  dft <- as.list(dft)

  dft <- as.data.frame(lapply(dft, type.convert))
  return(dft)
}

# Let's test it
(x <- read.transposed.xlsx("row-and-column-based-data.xlsx", sheet = 2))

x$var_1
x$var_3
```

**Comment by jennybc** [comment]
I think this is best handled by reading, transposing, and then (re-)doing type conversion. I don't see readxl gaining functionality to do this directly.

FYI `readr::type_convert()` will do type conversion in the readr / tidyverse style, if you want to try that out in your workflow. For example, `stringsAsFactors = FALSE` would be default behaviour.

**Comment by rappster** [comment]
@jennybc thanks for the pointer to `readr::type_convert()`!
