### ISSUE TITLE
free() on invalid pointer

### ISSUE THREAD

**Issue by wrathematics** [hadley/readxl#163]
Trying to read [this](https://www.dropbox.com/s/2qjgrxxlx06bxgv/exp.xlsx?dl=0) file with readxl produces the following:

```
> readxl::read_excel("exp.xlsx")
*** Error in `/usr/lib/R/bin/exec/R': free(): invalid pointer: 0x00000000028ccaa8 ***
Aborted
```

The [valgrind report](https://gist.github.com/wrathematics/53c761b3e8cdfce18e3c) doesn't look very useful to me, but I haven't taken a close look at the codebase.

The data is apparently just some random exponential, but was generated by and exported from JMP (it's for a homework problem, so blame my professor, not me). The exported file might be mal-formed somehow, but maybe not.  As I mentioned on twitter, the clang static analyzer `scan-build` (which I use to compile everything) throws several significant warnings when building readxl, though they appear to be coming from libxls.

**Comment by nacnudus** [comment]
The cells don't have the 'r' attribute that gives the cell address.  At the moment, readxl depends on that address, and doesn't guess by the cell's position in the xml.

**Comment by jennybc** [comment]
@nacnudus Agree.

Note to self: indicative xml in @wrathematics 's example:

``` xml
<worksheet xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main">
<dimension ref="A1:B31"/>
<sheetViews>...</sheetViews>
<sheetFormatPr defaultRowHeight="12.75"/>
<sheetData>
<row>
<c t="s">
<v>0</v>
</c>
<c t="s">
<v>1</v>
</c>
</row>
MORE ROWS
</sheetData>
<pageMargins left="0.7" right="0.7" top="0.75" bottom="0.75" header="0.3" footer="0.3"/>
</worksheet>
```

More typical and what readxl implicitly expects:

``` xml
<worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:mx="http://schemas.microsoft.com/office/mac/excel/2008/main" xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" xmlns:mv="urn:schemas-microsoft-com:mac:vml" xmlns:x14="http://schemas.microsoft.com/office/spreadsheetml/2009/9/main" xmlns:x14ac="http://schemas.microsoft.com/office/spreadsheetml/2009/9/ac" xmlns:xm="http://schemas.microsoft.com/office/excel/2006/main">
<sheetViews>
<sheetView workbookViewId="0"/>
</sheetViews>
<sheetFormatPr customHeight="1" defaultColWidth="14.43" defaultRowHeight="15.75"/>
<sheetData>
<row r="1">
<c r="A1" s="1" t="s">
<v>0</v>
</c>
<c r="B1" s="1" t="s">
<v>1</v>
</c>
<c r="C1" s="1" t="s">
<v>2</v>
</c>
<c r="D1" s="1" t="s">
<v>3</v>
</c>
<c r="E1" s="1" t="s">
<v>4</v>
</c>
<c r="F1" s="1" t="s">
<v>5</v>
</c>
</row>
MORE ROWS
</sheetData>
<drawing r:id="rId1"/>
</worksheet>
```
