### ISSUE TITLE
Error 103 when using read_excel() to read in .xlsx file

### ISSUE THREAD

**Issue by ikemblem** [hadley/readxl#164]
read_excel("sd02.xlsx", sheet = 1, skip = 2)

traceback()
5: stop(list(message = "error -103 with zipfile in unzGetCurrentFileInfo\n", 
       call = NULL, cppstack = NULL))
4: .Call("readxl_read_xlsx_", PACKAGE = "readxl", path, sheet, col_names, 
       col_types, na, nskip)
3: read_xlsx_(path, sheet, col_names = col_names, col_types = col_types, 
       na = na, nskip = skip)
2: read_xlsx(path, sheet, col_names, col_types, na, skip)
1: read_excel(file.path(path.drug, "tmp", "sd02.xlsx"), 
       sheet = 1, skip = 2)

[sd02.xlsx](https://github.com/hadley/readxl/files/192862/sd02.xlsx)

**Comment by nacnudus** [comment]
That file doesn't open in my copy of Excel 2016.  Are you sure it's an Excel file?

**Comment by jennybc** [comment]
Ditto what @nacnudus says.
