### ISSUE TITLE
Reading in merged cells - need to know number of columns they span

### ISSUE THREAD

**Issue by lindsaycarr** [hadley/readxl#166]
I am trying to read excel files that have merged cells as column names. In the example below, there is no way to determine that `Merged Column Name` applies to only `Column Name 1` and    `Column Name 2`, or that `Column name 2` corresponds to two columns of content.

It would be helpful if `read_excel` could give information about the number of  rows/columns that merged cells span. 

In Excel: 

<table>
  <tr>
    <td colspan="3">Merged Column Name</td>
    <td>                          </td>
    <td>                          </td>
  </tr>
  <tr>
    <td>Column Name 1 </td>
    <td colspan="2">Column Name 2</td>
    <td>Column Name 3</td>
    <td>Column Name 3</td>
  </tr>
  <tr>
    <td>Content</td>
    <td>Content</td>
    <td>Content</td>
    <td>Content</td>
    <td>Content</td>
  </tr>
</table>

Data frame in R looks like: 

<table>
  <tr>
    <td>Merged Column Name</td>
    <td>          NA            </td>
    <td>          NA            </td>
    <td>          NA            </td>
    <td>          NA            </td>
  </tr>
  <tr>
    <td>Column Name 1 </td>
    <td>Column Name 2</td>
    <td>          NA            </td>
    <td>Column Name 3</td>
    <td>Column Name 3</td>
  </tr>
  <tr>
    <td>Content</td>
    <td>Content</td>
    <td>Content</td>
    <td>Content</td>
    <td>Content</td>
  </tr>
</table>

**Comment by jennybc** [comment]
Is this the sort of R data frame you would expect in this case (I'm assuming you did not mean to repeat Column Name 3):

| Merged Column Name | Merged Column Name | Merged Column Name | something | else |
|--------------------|--------------------|--------------------|--------------------|--------------------|
| Column Name 1      | Column Name 2      | Column Name 2      | Column Name 3      | Column Name 4      |
| Content            | Content            | Content            | Content            | Content            |

Or maybe this?

| MCN.1   | MCN.2a   | MCN.2b   | something   | else   |
|---------|---------|---------|---------|---------|
| Content | Content | Content | Content | Content |

In any case, you might also be interested in the TableToLongForm package:

https://cran.r-project.org/web/packages/TableToLongForm/index.html
https://www.stat.auckland.ac.nz/~joh024/Research/TableToLongForm/
https://journal.r-project.org/archive/2014-2/oh.pdf

**Comment by burchill** [comment]
I've made a pull request that has the behavior of the first example @jennybc gave: #220 
However, be warned: column names that have the same name are a pain in the but.

**Comment by jennybc** [comment]
As discussed in #220 and above, it's best to handle these problems via other packages. There are no near term plans to get into merged cell issues here.
