### ISSUE TITLE
When Excel sheet tab names are numbers, read_excel finds those instead of using sheet as position

### ISSUE THREAD

**Issue by ahcyip** [hadley/readxl#168]
read_excel appears to be defaulting to looking for the sheet name but this causes a problem when sheet names are numbers themselves and I am actually asking Excel to use Sheet= as the position.

**Comment by jennybc** [comment]
Probably related to #80 and #104

**Comment by jennybc** [comment]
Until proven otherwise, I regard this as a duplicate of #104.
