### ISSUE TITLE
read_excel does not read the last column

### ISSUE THREAD

**Issue by spkal** [hadley/readxl#17]
read_excel does not read the last column in sheet

    read_excel("twocolumns.xlsx")
    ##    A
    ## 1  2
    ## 2  4
    ## 3  8
    ## 4 16
    ## 5 32
    # try with read.xls from the gdata package:
    library(gdata)
    read.xls("twocolumns.xlsx")
    ##    A  B
    ## 1  2  2
    ## 2  4  3
    ## 3  8  5
    ## 4 16  7
    ## 5 32 11
    
    sessionInfo()
    ## R version 3.1.3 (2015-03-09)
    ## Platform: x86_64-unknown-linux-gnu (64-bit)
    ## Running under: Ubuntu 14.04.2 LTS
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] gdata_2.13.3      readxl_0.0.0.9000
    ## 
    ## loaded via a namespace (and not attached):
    ## [1] gtools_3.4.1 Rcpp_0.11.5  tools_3.1.3

**Comment by hadley** [comment]
Curse you off-by-one errors!
