### ISSUE TITLE
Different NA values by column

### ISSUE THREAD

**Issue by dnchelst** [hadley/readxl#173]
I have data with multiple types of NA values. 
For example, 
- one character column will use "", 
- while a date column uses "**/**/****" 
- and a timestamp column uses "**:**:** **/**/****". 

Is there a way to specify more than one NA value?

**Comment by jennybc** [comment]
I would imagine that `readxl` will converge towards `readr` in terms of data ingest options. In the meantime, you could reprocess the affected variables with `readr::type_convert()`, which does support a vector of NA values.

**Comment by jennybc** [comment]
Multiple values for NA values covered by #13.
