### ISSUE TITLE
Single value option for col_types.

### ISSUE THREAD

**Issue by bedantaguru** [hadley/readxl#174]
I have a excel with 32 columns. What I wanted is that all of the columns should be treated as "text" [so no guessing for the columns type]. I can do that by writing `read_excel(path = file_name, sheet = sn, col_types = rep("text", 32))` but what if i don't know the number of columns and want to read all column by default as character so a syntax like `read_excel(path = file_name, sheet = sn, col_types = 'text')` should be ideal. I mean there should be an option to take a single input in col_types and replicate it during read time by number of columns. I think I can have a way around the problem by reading one line and detecting column numbers and then finally calling `read_excel` with number detected in earlier phase. 
Kindly let me know if this feature is going to be implemented soon.

**Comment by jennybc** [comment]
Duplicate of #127, #114.

**Comment by bedantaguru** [comment]
Sorry for duplicate. Closing the issue now.
