### ISSUE TITLE
Problems with variable names using accents and spaces

### ISSUE THREAD

**Issue by pachevalier** [hadley/readxl#177]
French people often use accents such as "é" or "è" and spaces in the variable names of their spreadsheet. That's a very bad practice but we have to deal with that when we work with other people on a project. Before moving to R version 3.3.0 the following program was running without error : 

```
library(readxl)
library(dplyr)
df <- read_excel("data/toto.xlsx")
df$`Ministère`
df %>% 
    select(Ministère)
```

Now df$`Ministère` doesn't return anything anymore and I don't know how to use `select()` and `mutate()` with long variable names such as `Ministère nom complet`. I don't know if this is due to dplyr or readxl 

[toto.xlsx](https://github.com/hadley/readxl/files/282448/toto.xlsx)

> devtools::session_info()
> Session info -----------------------------------------------------------------------------------------------------------
>  setting  value  
>  version  R version 3.3.0 (2016-05-03)
>  system   x86_64, linux-gnu  
>  ui       RStudio (0.99.878)  
>  language (EN)  
>  collate  fr_FR.UTF-8  
>  tz       <NA>  
>  date     2016-05-25                  

Packages ---------------------------------------------------------------------------------------------------------------
 package       \* version    date       source  
 ape             3.5        2016-05-24 CRAN (R 3.3.0)  
 assertthat      0.1        2013-12-06 CRAN (R 3.3.0)  
 chron           2.3-47     2015-06-24 CRAN (R 3.3.0)  
 colorspace      1.2-6      2015-03-11 CRAN (R 3.3.0)  
 data.table      1.9.6      2015-09-19 CRAN (R 3.3.0)  
 DBI             0.4-1      2016-05-08 CRAN (R 3.3.0)  
 devtools        1.11.1     2016-04-21 CRAN (R 3.3.0)  
 digest          0.6.9      2016-01-08 CRAN (R 3.3.0)  
 dplyr         \* 0.4.3      2015-09-01 CRAN (R 3.3.0)  
 DT            \* 0.1.56     2016-05-25 Github (rstudio/DT@68d5ec0)  
 flexdashboard \* 0.2.1      2016-05-25 Github (rstudio/flexdashboard@440cab3)
 ggdendro        0.1-20     2016-04-27 CRAN (R 3.3.0)  
 ggplot2         2.1.0      2016-05-24 Github (hadley/ggplot2@b181e9a)  
 gridBase        0.4-7      2014-02-24 CRAN (R 3.3.0)  
 gtable          0.2.0      2016-02-26 CRAN (R 3.3.0)  
 highcharter   \* 0.3.1.9999 2016-05-25 Github (jbkunst/highcharter@cb44c76)  
 htmltools       0.3.5      2016-03-21 CRAN (R 3.3.0)  
 htmlwidgets   \* 0.6        2016-02-25 CRAN (R 3.3.0)  
 httpuv          1.3.3      2015-08-04 CRAN (R 3.3.0)  
 igraph          1.0.1      2015-06-26 CRAN (R 3.3.0)  
 jsonlite        0.9.20     2016-05-10 CRAN (R 3.3.0)  
 knitr         \* 1.13       2016-05-09 CRAN (R 3.3.0)  
 lattice         0.20-33    2015-07-14 CRAN (R 3.2.1)  
 lazyeval        0.1.10     2015-01-02 CRAN (R 3.3.0)  
 lubridate     \* 1.5.6      2016-04-06 CRAN (R 3.3.0)  
 magrittr      \* 1.5        2014-11-22 CRAN (R 3.3.0)  
 MASS            7.3-45     2015-11-10 CRAN (R 3.2.2)  
 memoise         1.0.0      2016-01-29 CRAN (R 3.3.0)  
 mime            0.4        2015-09-03 CRAN (R 3.3.0)  
 munsell         0.4.3      2016-02-13 CRAN (R 3.3.0)  
 nlme            3.1-128    2016-05-10 CRAN (R 3.3.0)  
 plyr            1.8.3      2015-06-12 CRAN (R 3.3.0)  
 purrr           0.2.1.9000 2016-05-25 Github (hadley/purrr@2fd93d3)  
 quantmod        0.4-5      2015-07-24 CRAN (R 3.3.0)  
 R6              2.1.2      2016-01-26 CRAN (R 3.3.0)  
 RColorBrewer    1.1-2      2014-12-07 CRAN (R 3.3.0)  
 Rcpp            0.12.5     2016-05-14 CRAN (R 3.3.0)  
 readr         \* 0.2.2.9000 2016-05-25 Github (hadley/readr@870058a)  
 readxl        \* 0.1.1      2016-03-28 CRAN (R 3.3.0)  
 rlist           0.4.6.1    2016-04-04 CRAN (R 3.3.0)  
 rmarkdown       0.9.6      2016-05-01 CRAN (R 3.3.0)  
 rstudioapi      0.5        2016-01-24 CRAN (R 3.3.0)  
 scales        \* 0.4.0      2016-02-26 CRAN (R 3.3.0)  
 shiny           0.13.2     2016-03-28 CRAN (R 3.3.0)  
 stringi         1.0-1      2015-10-22 CRAN (R 3.3.0)  
 stringr         1.0.0      2015-04-30 CRAN (R 3.3.0)  
 tibble          1.0-5      2016-05-24 Github (hadley/tibble@19235d2)  
 tidyr         \* 0.4.1.9000 2016-05-25 Github (hadley/tidyr@32d9dd2)  
 treemap       \* 2.4-1      2016-03-26 CRAN (R 3.3.0)  
 tricky        \* 0.1        2016-05-25 Github (pachevalier/tricky@a5f3c0e)  
 TTR             0.23-1     2016-03-21 CRAN (R 3.3.0)  
 viridisLite     0.1.3      2016-03-12 CRAN (R 3.3.0)  
 withr           1.0.1      2016-02-04 CRAN (R 3.3.0)  
 xtable          1.8-2      2016-02-05 CRAN (R 3.3.0)  
 xts             0.9-7      2014-01-02 CRAN (R 3.3.0)  
 zoo             1.7-13     2016-05-03 CRAN (R 3.3.0)

**Comment by jennybc** [comment]
Can you provide, e.g. `data/toto.xlsx`?

## How to provide a readxl reprex

We're in a much better position to address your issue if you can provide a reprex (**repr**oducible **ex**ample). Provide as much of this as you can:

  * An actual xls or xlsx file. Pick one:
    - Your personal xls or xlsx: try to strip it down to the minimal size and complexity to demonstrate your point. And, obviously, remove any sensitive data.
    - A publicly available xls or xlsx: provide URL and the code you used to download.
  * A small bit of R code that uses readxl on the provided xls or xlsx file and demonstrates your point.
    - Consider using the [reprex package](https://github.com/jennybc/reprex#readme) to prepare this. In addition to nice formatting, this ensures your reprex is self-contained.
  * Any details about your environment that seem clearly relevant, such as operating system.
        `reprex(..., si = TRUE)`
    will append a standard summary, folded neatly away, at the bottom of your reprex.

How to provide your own xls/xlsx file? In order of preference:

  1. [Attach the file directly to your issue](https://help.github.com/articles/file-attachments-on-issues-and-pull-requests/). Instructions are always at the bottom of the issue or comment box.
  1. Share via DropBox or Google Drive and provide the link in your issue.
  1. Explain you absolutely cannot provide a relevant file via github.com and offer to provide privately.
  1. Don't share a file and realize you're hoping for, e.g., a bug fix with no concrete example to go on.

**Comment by pachevalier** [comment]
Here it is https://github.com/hadley/readxl/files/282448/toto.xlsx

**Comment by pachevalier** [comment]
Ok now it works with the following session : 

```
> session_info()
Session info -------------------------------------------------------------------
 setting  value                       
 version  R version 3.3.2 (2016-10-31)
 system   x86_64, linux-gnu           
 ui       RStudio (1.1.56)            
 language en_US                       
 collate  en_US.UTF-8                 
 tz       <NA>                        
 date     2017-01-31                  

Packages -----------------------------------------------------------------------
 package    * version    date       source                       
 assertthat   0.1        2013-12-06 cran (@0.1)                  
 DBI          0.5-1      2016-09-10 cran (@0.5-1)                
 devtools   * 1.12.0     2016-12-05 CRAN (R 3.3.2)               
 digest       0.6.11     2017-01-03 CRAN (R 3.3.2)               
 dplyr      * 0.5.0.9000 2017-01-20 Github (hadley/dplyr@165b760)
 lazyeval     0.2.0      2016-06-12 cran (@0.2.0)                
 magrittr     1.5        2014-11-22 cran (@1.5)                  
 memoise      1.0.0      2016-01-29 CRAN (R 3.3.2)               
 R6           2.2.0      2016-10-05 CRAN (R 3.3.2)               
 Rcpp         0.12.9     2017-01-14 CRAN (R 3.3.2)               
 readxl     * 0.1.1      2016-03-28 CRAN (R 3.3.2)               
 tibble       1.2        2016-08-26 cran (@1.2)                  
 withr        1.0.2      2016-06-20 CRAN (R 3.3.2)    

```
