### ISSUE TITLE
Umlauts causes R to crash

### ISSUE THREAD

**Issue by christianlindell** [hadley/readxl#184]
UPDATE: Now everything works after I updated R to 3.3.1 and dplyr to 0.5.

---

When I read an excel file that have swedish characters in the colum names the file seems all right but when I try to f.x sort the data frame by a colum with f.x a "ö" in the colname it causes R to crash. 

I'm running R 3.3.0 and RStudio Preview 0.99.1228 on Windows 7.

I know that the problem has to do with readxl because everything works when I read the excel file with XLConnect.

Example:

```
library(XLConnect)
library(readxl)
library(dplyr)


# Reading an excel file ("dat.xlsx") with 2 cols and 2 rows created in Excel 2013:
# region    col_ö
# A 1
# B 2


# reading with readxl (v 0.1.1):
df_readxl <- read_excel("dat.xlsx")


# reading with XLConnect
df_xlc <- readWorksheet(loadWorkbook("dat.xlsx"), 1)

# this works!
arrange(df_xlc, col_ö)

# this cause R to crash with a "fatal error"
arrange(df_readxl, col_ö)

# changing "ö" to "o" solves the problem
names(df_readxl)[2] <- "col_o"

# this works
arrange(df_readxl, col_o)
```

Session info --------------------------------------------------------------------------------------
 setting  value  
 version  R version 3.3.0 (2016-05-03)
 system   i386, mingw32  
 ui       RStudio (0.99.1228)  
 language (EN)  
 collate  Swedish_Sweden.1252  
 tz       Europe/Berlin  
 date     2016-06-20                  

Packages ------------------------------------------------------------------------------------------
 package       \* version date       source  
 assertthat      0.1     2013-12-06 CRAN (R 3.3.0)
 DBI             0.4-1   2016-05-08 CRAN (R 3.3.0)
 devtools        1.11.1  2016-04-21 CRAN (R 3.3.0)
 digest          0.6.9   2016-01-08 CRAN (R 3.3.0)
 dplyr         \* 0.4.3   2015-09-01 CRAN (R 3.3.0)
 lazyeval        0.2.0   2016-06-12 CRAN (R 3.3.0)
 magrittr        1.5     2014-11-22 CRAN (R 3.3.0)
 memoise         1.0.0   2016-01-29 CRAN (R 3.3.0)
 R6              2.1.2   2016-01-26 CRAN (R 3.3.0)
 Rcpp            0.12.5  2016-05-14 CRAN (R 3.3.0)
 readxl        \* 0.1.1   2016-03-28 CRAN (R 3.3.0)
 rJava           0.9-8   2016-01-07 CRAN (R 3.3.0)
 rsconnect       0.4.3   2016-05-02 CRAN (R 3.3.0)
 withr           1.0.1   2016-02-04 CRAN (R 3.3.0)
 XLConnect     \* 0.2-11  2015-03-01 CRAN (R 3.3.0)
 XLConnectJars \* 0.2-9   2014-08-14 CRAN (R 3.3.0)

**Comment by jennybc** [comment]
Glad various updates seemed to have solved it.
