### ISSUE TITLE
Problem with reading xls file

### ISSUE THREAD

**Issue by msgoussi** [hadley/readxl#185]
I have downloaded data from IMF website
http://www.imf.org/external/pubs/ft/weo/2016/01/weodata/download.aspx

either by country and country group.
I clicked right click and save file as filename.xls

Every time I try to use read_excel functions, it says it is not excel file.
I really appreciate if you could help me in that issue.

The file is not corrupted because if I open the file via Excel and re-save again as  xls file, the function works.

**Comment by christianlindell** [comment]
That's because it isn't an excel file, even i the file ending says so. It is atab delimited text file. Excel is smart enough to open it, even if it isn't an excel file because it have the .xls extension.

You can open it with Hadley Wickhams package "readr" , but with some errors:
```
library(readr)
dfIMF <- read_delim("http://www.imf.org/external/pubs/ft/weo/2016/01/weodata/WEOApr2016all.xls", 
                           "\t")
```

**Comment by msgoussi** [comment]
Dear mr. Hadley,
You are totaly right about excel. I would like to inform you that i managed
to read the file in r with read.csv function with sep="\t"  without any
errors.
I found out a website you upload the file and tell you exactly the type,
accordingly you choose the right package to use.
Thanks for you help.
Is there any function in r check the file type.
Have a nice day
