### ISSUE TITLE
Won't read non-lowercase .XLSX or .xlsm files

### ISSUE THREAD

**Issue by apjanke** [hadley/readxl#19]
Looks like the code for identifying the file type is being case-sensitive with extensions, so it will open `.xlsx` files but not `.XLSX`. 

    > read_excel("epoch-1900.XLSX")
    Error: Don't know how to parse extension XLSX

Since the extension-based file type detection on platforms Excel runs on is typically case-insensitive, it seems like `read_excel` should be too, with respect to detecting file formats.

It won't read `.xlsm` files, either. They're the same format as `.xlsx`, just with macros enabled.

    > read_excel("with-macro.xlsm")
    Error: Don't know how to parse extension xlsm

**Comment by hadley** [comment]
Want to try a pull request? It's a fairly simple fix

**Comment by apjanke** [comment]
Sure! Give me a little time, though; I'm an R newbie.

**Comment by apjanke** [comment]
All right, made a pull request for this, #20.
