### ISSUE TITLE
Reading a certain Excel (XLSX) file crashes R

### ISSUE THREAD

**Issue by huftis** [hadley/readxl#191]
Reading a certain XSLX file using `read_excel()` consistently crashes R, on both Windows (latest CRAN release, version 0.1.1) and Linux (latest GitHub release as of 2016-07-10). It results in this error message:

```
*** caught segfault ***
address 0x8, cause 'memory not mapped'

Traceback:
1: .Call("readxl_read_xlsx_", PACKAGE = "readxl", path, sheet, col_names,     col_types, na, nskip)
2: read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,     na = na, nskip = skip)
3: read_xlsx(path, sheet, col_names, col_types, na, skip)
4: read_excel("crashing.xlsx")

Possible actions:
1: abort (with core dump, if enabled)
2: normal R exit
3: exit R without saving workspace
4: exit R saving workspace
```

The file can be successfully loaded in both MS Excel and LibreOffice Calc. However, it was not created by Excel, but by some other tool. If I open it in Excel and save it as a new file, `readxl` can successfully open it.

There’s not any confidential data in the file, but I’d rather not make it public. So I’m sending it privately to @hadley.

**Comment by mcastagnaa** [comment]
Exactly the same issue for me: with a read_excel statement on a file generated by some other process I can't control I have:

```
Error in eval(substitute(expr), envir, enclos) : 
  Couldn't find 'xl/worksheets/sheet2.xml' in '\\uknasprd01/RISK_TECH/risk_share/inbound/FFTS/GROUP3var 09-29 14-17.xlsx'

```
If I run the same statement in R Studio I have the crashing bomb.

**Comment by jennybc** [comment]
@huftis Can you provide that xlsx to me? jenny@stat.ubc.ca

@mcastagnaa I think you have a different problem, more likely related to #80. Are you able to share such a file? If so, please continue the conversation over on #80.

**Comment by huftis** [comment]
@jennybc I have now sent you the Excel file that crashes R, along with a similar file that doesn’t crash R. (The crashing file was created some non-Excel tool and the non-crashing file was created by opening the crashing file in Excel and resaving.)

**Comment by jennybc** [comment]
Thanks @huftis I got the email. 👍

Can you tell me the name of the tool that creates the difficult sheet? This is a common theme in many issues and it would be helpful to know if we're dealing with lots of sheets from a single tool (maybe same problem?) or singles from many tools (who knows?).

**Comment by mcastagnaa** [comment]
Hi, thanks,
kind of funny I must say.
I changed the code and instead of defining the wb and then reading it, I go
straight to the reading bit and it all works.

Regards. Matteo

**Comment by huftis** [comment]
@jennybc According to the provider of the file, they use http://epplus.codeplex.com/ to generate Excel files.

**Comment by mcastagnaa** [comment]
Hi, just attached the file which caused the issue with the readxl 
package to #80 <https://github.com/hadley/readxl/issues/80>

**Comment by larspett** [comment]
I am having the same bomb shutdown issue with RStudio and an Excel .xls file in Windows but not in OSX. The import script is identical and the path the same (a shared Box directory). Libraries etc are up to date. The file appears to have been created in Excel. Windows bombs, Mac does not.

Best wishes, Lars

**Comment by larspett** [comment]
Update: The downloaded file made in Excel did indeed import whereas a renamed & saved version (using download.file to xls) opened fine in OSX but bombs in Windows. Hence it was a non-excel made xls causing problems in this case too. Best, Lars

**Comment by GioBo** [comment]
I am having the same problem reported by huftis when attempting to import the xls file available at [http://bit.ly/2m16uyE](http://bit.ly/2m16uyE); using readxl_0.1.1 on R-devel under Ubuntu 16.04.

**Comment by jennybc** [comment]
@GioBo 

  1. Please try with the development version of readxl, installed from GitHub, not CRAN.
  2. Make sure you use `download.file(..., mode = "wb")` if you are on Windows and that could have anything to do with this.

**Comment by GioBo** [comment]
@jennybc 

     Thanks for the answer: the problem persists with the GitHub version of the package (and yes, I checked that `download.file(..., mode = "wb")` ). I am not the author of the Excel file, thus I do not know how that was generated, but I guess the problem lies in that file... I've never had issues with `read_excel( )` before with other files.

**Comment by jennybc** [comment]
@GioBo OK I will have a look. Thanks for providing link.

**Comment by jennybc** [comment]
@GioBo Trying to open this workbook causes my R/RStudio to crash. From inspecting it in Excel, I notice that the sole worksheet is password protected, so I have some concern that this may not be compatible with libxls, which readxl uses to parse xls files. I will do a bit more investigation. But FWIW you can do "Save As ...", save a copy, and then it imports just fine.

**Comment by jennybc** [comment]
Based on what I see in the debugger, I strongly suspect this is a problem with libxls and password-protected worksheets in xls. Which appears to be fairly rare, so my recommendation is to just save a fresh copy of this file and use `read_excel()` on that.

**Comment by darhallas** [comment]
I was also having an issue. In my case it seemed to be because the .xls file did not have an author so my only option was to open it and save it again. Is there another way around this? The are a lot of files that I am looping through and would prefer to not have to open and resave each one.

**Comment by jennybc** [comment]
My understanding of this hasn't advanced since last time I was here. No new ideas and I'm afraid it's not the right combination of common enough problem + easy enough fix to become a very high priority for readxl.
