### ISSUE TITLE
Add Feature: Read Integer

### ISSUE THREAD

**Issue by alexhallam** [hadley/readxl#205]
I was recently reading a file and wanted to read one column as an integer as follows:

data= read_excel("<filename>", sheet = 1,col_names = TRUE,col_types = c("text","integer","numeric","blank"),na="N/A") 

It seems to me, that their is no way of reading integers. When I specify the column as "numeric" the data is cast to a double. It would be nice to read data as integer. 

If this is already and I am just not implementing it correctly I apologize.

**Comment by jennybc** [comment]
Covered by #198
