### ISSUE TITLE
Feature Request: Expose read_xls_col_types argument "n"

### ISSUE THREAD

**Issue by billdenney** [hadley/readxl#206]
I have files which I would prefer to auto-detect the column types for.  It has a column that from row 1 to 150 has numbers, and starting around element 151 has the text "Missing", and most columns have missing indicated by "".  (Because of #136 and #197, I can't just say na=c("", "Missing").)

It would be helpful if the "n" argument of the xls_col_types function were exposed to the main read_excel function so that I don't have to do the following:

```
my_read_excel <- function(..., n_col_type=100, skip=0) {
  my_col_types <- readxl:::xls_col_types(..., nskip=skip, n=n_col_type)
  read_excel(..., skip=skip, col_types=my_col_types)
}
```

**Comment by MilesMcBain** [comment]
Or alternately export the `xls_col_types` function. There is precedent for this in `readr` where `guess_parser` and `parse_guess` were exported. Similar utility here would be appreciated.

**Comment by jennybc** [comment]
Covered by #223
