### ISSUE TITLE
Standardize Argument Names

### ISSUE THREAD

**Issue by billdenney** [hadley/readxl#207]
While figuring out how to work around #206, I noted that argument names, values, and order are not standardized through the package.  This makes it much more difficult to work through issues.

Examples:
- `sheet`
  - read_excel default = 1
  - xls_col_types default = 0
- `skip` (from read_excel)
  - named `nskip` in `xls_col_types`, `read_xlsx_`, `xls_col_names`, `xls_cols`
- `path` is used when in most reading functions (like `read.csv`) the name of the argument is `file`

**Comment by jennybc** [comment]
Thanks. Will bear this in mind during upcoming maintenance.
