### ISSUE TITLE
date import works in Windows, but not in GNU/Linux

### ISSUE THREAD

**Issue by iembry-USGS** [hadley/readxl#218]
I have a .xlsx spreadsheet named [date_test.xlsx](https://github.com/hadley/readxl/files/632988/date_test.xlsx), where the data follow:

Date	         Amount
01/01/15	 $27.26 
01/02/15	 $38.06 
01/04/15	 $19.33 
01/05/15	 $13.88 
01/05/15	 $27.18 
01/05/15	 $24.04 
01/05/15	 $70.26 
01/06/15	 $28.06 
01/06/15	 $216.62 
01/07/15	 $86.85 

In R, I have the following code:

library(readxl)
read_excel("date_test.xlsx")

On Windows, the result is the Date becomes a POSIXct object with the correct Date; however, on GNU/Linux, I am getting the Date as a numeric object. The numeric object can not be converted to Date using `lubridate`'s ymd().

Can you test importing spreadsheets on both MS Windows and GNU/Linux that have date columns?

Thank you.

**Comment by zeehio** [comment]
Try building the package from this PR to see if the issue is fixed:
https://github.com/hadley/readxl/pull/165. From R you can do:

    devtools::install_github("zeehio/readxl@fix_datetimes_libreoffice")

**Comment by iembry-USGS** [comment]
@zeehio   Thank you. That resolved the issue.
