### ISSUE TITLE
Error: Invalid sheet xml (no <dimension>) from some xlsx files created by Google Sheets

### ISSUE THREAD

**Issue by jrnold** [hadley/readxl#26]
I've gotten the error `Invalid sheet xml (no <dimension>)` message several times when trying to open up `xlsx` files created from spreadsheets on Google Sheets. This may be because they aren't following the spec, but I'm not sure. This appears to be a Google Sheets problem because I was able to open the spreadsheet using LibreOffice, and when I saved it back to an xlsx file using LibreOffice `read_excel` opened it without error.

Here's an example spreadsheet (it's just the iris data) for which I get this error. Open the spreadsheet https://drive.google.com/open?id=10lVYeaRV1hK8aPmhNuTyx5YXSFQC3cL5VmNppZ0u8_Q&authuser=0 and download it as Excel or download the xlsx file which was created from that spreadsheet: https://drive.google.com/open?id=0B3SVyot2nUtGWkhiekRSUjZENkk&authuser=0. 
Then,
```
> read_excel("readxl_test.xlsx")
Error: Invalid sheet xml (no <dimension>)
```

**Comment by hadley** [comment]
It's an optional part of the spec, but all the docs I created had it so I was relying on it. I can add a fallback.

**Comment by jrnold** [comment]
Awesome. Great work as usual!
