### ISSUE TITLE
Time without date error

### ISSUE THREAD

**Issue by okumuralab** [hadley/readxl#27]
XLS files with times without dates, such as "12:34:56", give warnings like

 1: In xls_cols(path, sheet, col_names = col_names, col_types = col_types,  :
   Expecting date in [1, 2] got 0.524259

and result in <NA>.

For XLSX files, "12:34:56" results in "1899-12-30 12:34:56", which is awkward but allowable.

**Comment by hadley** [comment]
Can you send me the sheet? It may be because I'm only checking for m, d and y etc in the format strings, not the Japanese equivalents. 

Times are hard in general because R doesn't have a built in time type.

**Comment by okumuralab** [comment]
Thanks!
Now all of the examples I tested worked fine with the newest version.
(Except for the "1899-12-30 12:34:56" problem that cannot be solved easily.)

**Comment by hadley** [comment]
Thanks! I'm pleasantly surprised that I've correctly plumbed together UTF-8 support so the Japanese characters just work :)
