### ISSUE TITLE
Unable to read file unless I open and re-save it

### ISSUE THREAD

**Issue by smach** [hadley/readxl#28]
FYI I downloaded this test file: 
https://github.com/onyxfish/csvkit/raw/master/examples/realdata/ne_1033_data.xlsx

When I tried to read it with read_excel() I got an error message

Error: Invalid sheet xml (no <dimension>)

(that's Error: Invalid sheet xml (no &lt;dimension>) 

When I opened the file in Excel and then saved it without doing anything else to it, read_excel() was able to parse it. This happened on my Windows machine.

**Comment by hadley** [comment]
Was probably created in google docs so didn't have explicit dimension tag. Fixed now.
