### ISSUE TITLE
Error message when trying to install on OS X Yosemite

### ISSUE THREAD

**Issue by smach** [hadley/readxl#29]
This is a new system, so I'm not 100% sure the problem is with readxl and not something amiss with my system. However,I have been able to install other packages from GitHub OK. But FYI when I try to install readxl, I see these messages:

Downloading github repo hadley/readxl@master
Installing readxl
'/Library/Frameworks/R.framework/Resources/bin/R' --vanilla CMD INSTALL  \
  '/private/var/folders/l9/[specific path]'  \
  --library='/Library/Frameworks/R.framework/Versions/3.1/Resources/library' --install-tests 

* installing *source* package ‘readxl’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -Iunix -I. -I/usr/local/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"   -fPIC  -mtune=core2 -g -O2  -c RcppExports.cpp -o RcppExports.o
In file included from RcppExports.cpp:4:
In file included from /Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp.h:27:
In file included from /Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/RcppCommon.h:29:
/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include/Rcpp/platform/compiler.h:95:10: fatal error: 'cmath' file not found
#include <cmath>
         ^
1 error generated.
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘readxl’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/readxl’
Error: Command failed (1)

**Comment by hadley** [comment]
I'd say something is messed up in your install: cmath is super important.

**Comment by smach** [comment]
FYI the installation error message was because OS X requires installation of XCode in order for this to run. I had done that so long ago on my old Mac that I'd pretty much forgotten about it. You may want to mention in the installation instructions that Mac OS X requires XCode to be installed (easy enough from the app store) in order for readxl to be installed, since some people trying to run basic R code on their systems may not have done that already.
