### ISSUE TITLE
check.names default (and reading from URL)

### ISSUE THREAD

**Issue by grantmcdermott** [hadley/readxl#34]
Great package. Two minor issues:

1) Can we add a check.names option (set to FALSE as default) for read_excel? Multi-word column names are currently being read "as is" from Excel, rather than having spaces replaced with periods.

2) I may have missed something, but is it possible to read .xls files directly from a URL?

**Comment by hadley** [comment]
My philosophy is not to munge column names since you can easily refer to full names using (e.g.) `` `a b` . ` It's not currently possible, but I'll think about how to enable it - it will just be a wrapper around downloading the file, so it's not a big win.
