### ISSUE TITLE
Rounding error when numbers are interpreted as characters

### ISSUE THREAD

**Issue by grahamrp** [hadley/readxl#37]
If I create a simple Excel worksheet like

|col1|
|---|
|73.1|

`read_excel('minimal.xlsx')`

works as expected, interpreting col1 as type *num* and the value as *73.1*

But if I then add a character value "x" in the next row like this

|col1|
|---|
|73.1|
|x|

now col1 is interpreted as type *char* but the value changes to *73.099999999999994*

The strange rounding happens to some numbers but not others.

I'm using Excel 2010 on 32-bit Windows 7 and readxl 0.0.0.9000

**Comment by hadley** [comment]
Yup, that's how floating point numbers work.
