### ISSUE TITLE
import with swedish characters å,ä,ö

### ISSUE THREAD

**Issue by janzzon** [hadley/readxl#38]
Swedish characters å,ä,ö in the excel-file changes to <e5>,<e4>,<f6> in the imported data.
The same file saved as .csv and imported by read.csv2() passes the original å,ä,ö into the data.

**Comment by hadley** [comment]
Could you please upload a simple example and link to it from here?

**Comment by janzzon** [comment]
Tried a little bit more, works with .xlsx but fails with .xls
Two examples linked from my dropbox
https://www.dropbox.com/sh/pi4676zj5obyivu/AADQMY5A8QN6D9Lbf1OlIZjsa

**Comment by f34739** [comment]
What I get for the same characters is " \xe5,\xe4,\xf6" - why that?

**Comment by janzzon** [comment]
Ooops, I see now that github did something evil to the failing symbols in my first post. The import of å,ä,ö in xls-format translates to " <e5>,<e4>,<f6>".

**Comment by hadley** [comment]
This was a very very small mistake ;) For future reference, use `` ` `` to surround code/data so that github doesn't munge it, e.g. `<e5>,<e4>,<f6> `
