### ISSUE TITLE
Missing columns due to blank cells underneath column header

### ISSUE THREAD

**Issue by chrisaxelson** [hadley/readxl#40]
Thanks so much for a great (and speedy) package!

Just to let you know that the read_excel function doesn't seem to import columns if the initial data in those columns are blank. The xlsx in the link has 295 columns but only the first column is imported. The rows aren't blank as the first column does contain data. 

I see you're discussing anchors and specifying ranges which would make it possible to manually identify, but it might still be useful if the default brought it all in.

```
library(readxl)
download.file("https://www.resbank.co.za/Lists/News%20and%20Publications/Attachments/6648/01Kbp1%20%E2%80%93%20Money%20and%20Banking%20%E2%80%93%20March%202015.zip", "Banking_data.zip")
unzip("Banking_data.zip")
ncol(read_excel("Kbp1MB-March2015.xlsx", sheet = "M1"))
#2
```

Thanks again for all your hard work!

**Comment by hadley** [comment]
This seems to be ok now:

```R
 tail(read_excel("~/Desktop/Kbp1MB-March2015.xlsx"))
           NA KBP1434D KBP1437D KBP1438D KBP1440D KBP1456D KBP1457D
5299 20150131     2561    37800        0    40717     1256      900
5300 20150202        0    37800        0    41881     4583      502
5301 20150203        0    37800        0    40790     3230      241
5302 20150204        0    37500        0    40619     3363      244
5303 20150205        0    37500        0    38806     1611      305
5304 20150206        0    37500        0    37940     1433      993
```

**Comment by chrisaxelson** [comment]
Hi Hadley,

Sorry I'm really not trying to be a pain - it's the fourth sheet in the xlsx file that has the issue. There are 295 columns but code will import first 2 only.

````
tail(read_excel("~/Desktop/Kbp1MB-March2015.xlsx"), sheet = 4)
````
Thanks again for all your work on readr, readxl and haven lately!

**Comment by reinierv4** [comment]
I have a similar problem. When I try to read in a .xls file downloaded and saved from the internet R reads in the file without the last column. When I manually open and save my excel file and try to read in the file again this problem disappears. This is however not a feasible workaround because of the amount of files I have to process. Would be great if somebody has a solution!

**Comment by hadley** [comment]
@reinierv4 please file a new issue with a minimal reproducible example (i.e. including a link to the file to download)

**Comment by reinierv4** [comment]
Hi Hadley, thanks a lot for your quick response. I created a new issue: https://github.com/hadley/readxl/issues/99
