### ISSUE TITLE
Failure in guessing col_types result in warnings an NA-values

### ISSUE THREAD

**Issue by janzzon** [hadley/readxl#42]
When a column in the excel-file have numeric values in the first rows, and text further down in the column, the "guess col_types" will set col_types to numeric. The import will give warnings and the non-numeric values will be NA.
Suggestion is to re-evaluate the content of whole column if the error-message appear, and then import with suitable format.
Another solution may be to just fall back to set col_types for that column to "text" and reimport if there's a error message of not matching data types.

I've linked 2 example docs from my dropbox, one working and one failing.
https://www.dropbox.com/sh/8mzk6z12f99ye4w/AABe-C7fxCzm1lomNyge1pw_a?dl=0

File "working_numeric_import_small.xlsx" have non-numeric data in early rows, so that import works by just runng read_excel("working_numeric_import_small.xlsx")

The file "error_numeric_import.xlsx" have numerical data in the first rows, but other characters in later rows.
Running 'read_excel("error_numeric_import.xlsx")' will give the following warnings:

Warning messages:
1: In read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  ... :
  [181, 3]: expecting numeric: got '555-55555'
2: In read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  ... :
  [184, 3]: expecting numeric: got 'tel +46-70-55555888'
3: In read_xlsx_(path, sheet, col_names = col_names, col_types = col_types,  ... :
  [294, 2]: expecting numeric: got '123736/1''
...
...

**Comment by hadley** [comment]
This is not the philosophy of readxl (and readr) - if you have column types that don't read in correctly by default, you'll need to supply the types explicitly. Hopefully the warnings are a hint to do this.  (I need to document this better, and probably provide a nicer way to override the defaults)

**Comment by janzzon** [comment]
Any suggestion of R-code to use with read_excel to identify the problematic columns, define those as text, and use the automatic detection for the columns that's correctly identified?

**Comment by hadley** [comment]
I'm probably going to change the format of the warnings so that you can get a data frame that includes rows and columns of the errors. Then you'd be able to write what you need.

**Comment by mielniczuk** [comment]
In r markdown proj documentation have {r opts, echo=FALSE, message=FALSE, warning=FALSE} yet readxl still produced warnings on cols not part of the analysis. Adding  {r readxl, echo=TRUE, eval=TRUE, warning=FALSE} again in the data import code block solved the problem. Would be nice to suppress on import.
