### ISSUE TITLE
local install of package fail

### ISSUE THREAD

**Issue by yonicd** [hadley/readxl#46]
i am running in an offline enviornment and downloaded the master zip file to run
    devtools::install_local("readxl-master.zip")
it is looking for dependencies (Rcpp) and it tries to download the package by default and fails, even though Rcpp is already installed. 
> installed.packages()%>%data.frame(row.names = NULL)%>%filter(str_detect(Package,glob2rx("Rc*")))%>%select(Package,Version)

        Package   Version
1          Rcpp    0.11.4
2 RcppArmadillo 0.4.320.0
3     RcppEigen 0.3.2.1.2

If i try to run 
    devtools::install_local("readxl-master.zip",dependencies=F)
i also get an error 
    > library("devtools", lib.loc="~/R/win-library/3.1")
    > install_local("w:\\r_packages\\readxl-master.zip",dependencies=F)
     Installing package from w:\r_packages\readxl-master.zip
    Installing readxl
    "C:/Users/u243/DOCUME~1/R/R-31~1.2/bin/i386/R" --vanilla CMD INSTALL  \
    "C:\Users\u243\AppData\Local\Temp\2\RtmpOYZ3j3\devtoolsf082dac658\readxl-master"  \
     --library="C:/Users/u243/Documents/R/win-library/3.1" --install-tests 
* installing *source* package 'readxl' ...
** libs
Warning: running command 'make -f "Makevars.win" -f "C:/Users/u243/DOCUME~1/R/R-31~1.2/etc/i386/Makeconf" -f "C:/Users/u243/DOCUME~1/R/R-31~1.2/share/make/winshlib.mk" SHLIB_LDFLAGS='$(SHLIB_CXXLDFLAGS)' SHLIB_LD='$(SHLIB_CXXLD)' SHLIB="readxl.dll" OBJECTS="RcppExports.o XlsWorkBook.o XlsWorkSheet.o XlsxWorkBook.o XlsxWorkSheet.o benchmarks.o endian.o ole.o xls.o xlstool.o zip.o"' had status 127

ERROR: compilation failed for package 'readxl'

* removing 'C:/Users/u243/Documents/R/win-library/3.1/readxl'

Error: Command failed (1)

**Comment by hadley** [comment]
Might be easier if you just wait for a CRAN release - I'm planning for one very soon.

**Comment by yonicd** [comment]
Ive met this error in a few packages trying to install locally git based
projects. Is there a good solution for this type of problem?

**Comment by jakesherman** [comment]
I was having this same issue installing the readxl package during an active R session. I restarted the session, and installed the package before loading any other packages, and it worked!

**Comment by danilolimoeiro** [comment]
I'm also trying to use this package but getting error below. Looking forward to have it released at CRAN.

xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
ERROR: compilation failed for package ‘readxl’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/readxl’
Error: Command failed (1)
