### ISSUE TITLE
New line in cell can create _x000D_

### ISSUE THREAD

**Issue by janzzon** [hadley/readxl#51]
Some types of new lines in excel-cell looks ok in excel, but adds
``` _x000D_ ``` when imported with read_excel.
Example in my dropbox, file "New line errors.xlsx"
https://www.dropbox.com/sh/8mzk6z12f99ye4w/AABe-C7fxCzm1lomNyge1pw_a?dl=0

**Comment by hadley** [comment]
How did you create the file? If I resave it, it seems to load in ok.

The xml literally looks like this:

```xml
<sst xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" count="3" uniqueCount="3">
  <si>
    <t>column_name</t>
  </si>
  <si>
    <t>first line of text _x000D_
second line of text _x000D_
i don&apos;t know what type of line feed I&apos;ve used _x000D_
last line</t>
  </si>
  <si>
    <t>Will show &quot;_x005F_x000D_&quot; in every new line in cell above</t>
  </si>
</sst>
```

@jmarshallnz any thoughts? @evanmiller have you seen this before?

(This seems related: http://stackoverflow.com/questions/14944456/datatable-writexml-how-to-preserve-spaces-in-element-names)

**Comment by jmarshallnz** [comment]
Here's another example of this.  Seems Excel is using a weird way of storing hex entities?

**Comment by jmarshallnz** [comment]
And another from apache, which refers to this being in the OOXML spec (but no reference unfortunately)

https://bz.apache.org/bugzilla/show_bug.cgi?id=49653

**Comment by hadley** [comment]
@jmarshallnz plus I'm pretty sure you _can_ represent a carriage return in XML (since it's a unicode character)
