### ISSUE TITLE
Issue with compilation, asprintf

### ISSUE THREAD

**Issue by IainNZ** [hadley/readxl#59]
Hi @hadley,

I just tried to install this package (`devtools::install_github("hadley/readxl")`), and got a compilation error:

```
clang -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -Iunix -I. -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c xlstool.c -o xlstool.o
xlstool.c:167:12: error: static declaration of 'asprintf' follows non-static declaration
static int asprintf(char **ret, const char *format, ...)
           ^
/usr/include/stdio.h:453:6: note: previous declaration is here
int      asprintf(char ** __restrict, const char * __restrict, ...) __printflike(2, 3);
         ^
1 error generated.
make: *** [xlstool.o] Error 1
ERROR: compilation failed for package ‘readxl’
* removing ‘/Library/Frameworks/R.framework/Versions/3.1/Resources/library/readxl’
Error: Command failed (1)
```

Here is the output from version

```
> version
               _                           
platform       x86_64-apple-darwin13.4.0   
arch           x86_64                      
os             darwin13.4.0                
system         x86_64, darwin13.4.0        
status                                     
major          3                           
minor          1.3                         
year           2015                        
month          03                          
day            09                          
svn rev        67962                       
language       R                           
version.string R version 3.1.3 (2015-03-09)
nickname       Smooth Sidewalk   
```

I'm on OSX 10.9, if thats helpful info too.

Something on my end?

**Comment by hadley** [comment]
I think if you try again now it will be ok. Working on some cross-platform C issues.

**Comment by IainNZ** [comment]
Works great, thanks!

**Comment by rhurlin** [comment]
I have the same problem, described above, on FreeBSD with R-devel. I tried this on two ways, with same result:
R CMD INSTALL readxl_0.1.0.tar.gz
devtools::install_github("hadley/readxl")

[..snip..]
gcc48 -std=gnu99 -I/usr/local/lib/R/include -DNDEBUG -Iunix -I. -I/usr/local/include -DLIBICONV_PLUG -I"/usr/local/lib/R/library/Rcpp/include"   -fpic  -O2 -pipe  -fno-builtin-erfcl -fno-builtin-powl -fno-builtin-sinhl -fno-builtin-tgammal -DLIBICONV_PLUG -fstack-protector -Wl,-rpath=/usr/local/lib/gcc48 -fno-strict-aliasing  -c xlstool.c -o xlstool.o
xlstool.c:167:12: error: static declaration of 'asprintf' follows non-static declaration
 static int asprintf(char **ret, const char *format, ...)
            ^
In file included from xlstool.c:38:0:
/usr/local/lib/gcc48/gcc/x86_64-portbld-freebsd11.0/4.8.5/include-fixed/stdio.h:410:6: note: previous declaration of 'asprintf' was here
 int  asprintf(char **, const char *, ...) __printflike(2, 3);
      ^
*** Error code 1
Stop.
make: stopped in /tmp/RtmpaqXsxu/devtools4c7e361915db/hadley-readxl-7c7f66b/src
ERROR: compilation failed for package ‘readxl’


So it seems, that the problem with asprintf() is only solved for OSX?
Any help is really appreciated. Thanks in advance.

Reagards,
Rainer Hurling

-----
> version
platform       amd64-portbld-freebsd11.0                         
arch           amd64                                             
os             freebsd11.0                                       
system         amd64, freebsd11.0                                
status         Under development (unstable)                      
major          3                                                 
minor          3.0                                               
year           2015                                              
month          09                                                
day            04                                                
svn rev        69292                                             
language       R                                                 
version.string R Under development (unstable) (2015-09-04 r69292)
nickname       Unsuffered Consequences                           

-----
> sessionInfo()
R Under development (unstable) (2015-09-04 r69292)
Platform: amd64-portbld-freebsd11.0 (64-bit)
Running under: FreeBSD xxx.xxx.xxx 11.0-CURRENT FreeBSD 11.0-CURRENT #0 r287160: Wed Aug 26 14:02:53 CEST 2015     xxx@xxx.xxx.xxx:/usr/obj/usr/src/sys/XXX  amd64

locale:
[1] C/de_DE.UTF-8/de_DE.UTF-8/C/de_DE.UTF-8/de_DE.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] httr_1.0.0      R6_2.1.1        magrittr_1.5    rversions_1.0.2 tools_3.3.0     curl_0.9.3     
 [7] Rcpp_0.12.0     memoise_0.2.1   xml2_0.1.2      stringi_0.5-5   git2r_0.11.0    stringr_1.0.0  
[13] digest_0.6.8    devtools_1.8.0
