### ISSUE TITLE
Column names like "First column" result in "First.column", why not "First_column"?

### ISSUE THREAD

**Issue by petermeissner** [hadley/readxl#61]
When reading sheets that have column names with restricted characters readxl replaces them with `"."` since the use of `"."` is a little ambiguous in R why not use `"_"` instead - as all Hadley packages and book would suggest anyways. 

**Maybe an *replacement-character-for-characters-not-to-be-used-in-column-names*-option would be a way to go**

**Comment by grssnbchr** [comment]
Weirdly, in my case, this replacement does not work. I have, for example the column "Gemeinde-Nummer". This stays "Gemeinde-Nummer" after reading in, but I can't reference it like so, for example: `mydata$Gemeinde-Nummer`. This gives: `Error: object 'Nummer' not found`.

**Comment by petermeissner** [comment]
in regard to the referencing have a look at this ... 
```
mydata <- list('g-n'=1)

# does not work
mydata$g-n

# ... because R is trying to do mydata$g minus n 
mydata$g <- 2
n <- 4
mydata$g - n 


# but this works 
mydata$`g-n`
```

**Comment by grssnbchr** [comment]
Ok thanks.. but how do I use it with `dplyr`?
For example, `mydata %>% rename(GN = Gemeinde-Nummer)` gives an error, too.

**Comment by petermeissner** [comment]
I cannot reproduce that. Data frames seem to refuse `"-"` as part of the name and transform it to `"."` instead : 

```r
mydata = data.frame(`g-n` = 1, normal = 2)
mydata
##   g.n normal
## 1   1      2
```

... could you give an minimal example ?

**Comment by hadley** [comment]
Just put backticks around weird names: ``mydata %>% rename(GN = `Gemeinde-Nummer`)``
