### ISSUE TITLE
Issues with special characters on Windows machine.

### ISSUE THREAD

**Issue by petermeissner** [hadley/readxl#63]
Reading a table with names containing special characters something like `"Günther"` results in `"G\xf6tz"` causing problems along the way: E.g. neither grepl() and str_extract() do not work as expected ... 

...  **while something like this works on handwritten data ...**

    str_extract("G\xfcnther", "ü")
    ## ü 

    str_extract("G\xfcnther", "\xfc")
    ## "ü"

**... it does not work on the data read in by readxl.** My current workaround is to use `iconv(column)` without any further parameters to get values from `"G\xf6tz"` to `"Günther"`. From then on everything works fine. 

My guts tell me, that this is probably one of those R-Windows-Locale-Encoding issues as I use Windows and am used strange happening with characters when read into R.

**Comment by hadley** [comment]
Are you sure you're using the latest version? I'm pretty sure I fixed this problem. If not, please provide a reproducible example.

**Comment by petermeissner** [comment]
I am very sorry - my fault. I had indeed version 0.9 instead of 1.0. With 1.0 there are no problems of this kind.
