### ISSUE TITLE
Problem in loading the xlsx sheet link

### ISSUE THREAD

**Issue by shankarchari** [hadley/readxl#67]
I am trying to load the file downloaded from data.gov site. Realized there is an issue.
Refer the attached image, first column name should be "Zip" but the realized value is empty. Similarly 6th column name should be "Ext" but it is written as .5.
Further, 19 x .5 should be 11. 

http://catalog.data.gov/dataset/natural-gas-acquisition-program

![gas](https://cloud.githubusercontent.com/assets/637224/7122439/0439e878-e239-11e4-82a7-420542761f3f.png)

**Comment by shankarchari** [comment]
This is part of my Coursera course exercise.

**Comment by jennybc** [comment]
readxl works as advertised on this file:

``` r
library(readxl)
library(here)
#> here() starts at /Users/jenny/rrr/readxl
df <- read_excel(here("iss", "DATA.gov_NGAP.xlsx"))
#df
#df %>% View()
df[17:23, 7:15]
#>                 .1        .2        .3           .4   .5           .6
#> 17   Zip CuCurrent PaCurrent PoCurrent      Contact  Ext          Fax
#> 18 74136         0         1         0 918-491-6998    0 918-491-6659
#> 19 30329         1         0         0 404-321-5711 <NA>         <NA>
#> 20 74136         1         0         0 918-523-2516    0 918-523-2522
#> 21 80203         0         1         0 303-864-1919    0         <NA>
#> 22 80120         1         0         0 345-098-8890  456         <NA>
#> 23  <NA>      <NA>      <NA>      <NA>         <NA> <NA>         <NA>
#>       .7     .8
#> 17 email Status
#> 18  <NA>      1
#> 19  <NA>      1
#> 20  <NA>      1
#> 21  <NA>      1
#> 22  <NA>      1
#> 23  <NA>   <NA>
```

I think you want to read just that sub-table, which is not currently possible but is coming (#8).

> Further, 19 x .5 should be 11.

You're referring to cell L20, which is truly empty. The "11" you're seeing is just last two digits of the adjacent phone number (?) in K20.
