### ISSUE TITLE
Reads in all 65'523 rows

### ISSUE THREAD

**Issue by grssnbchr** [hadley/readxl#69]
I think the maximum number of rows in a XLSX document is 65'523. 
When I read in sheets with far fewer rows (e.g., 2500 rows), the resulting data frame still has this huge number of (empty) rows. Is there a way to prevent `read_excel()` from doing this?

**Comment by hadley** [comment]
Typically this is because the sheet actually contains those rows, but they're empty.  #22 will fix the problem.
