### ISSUE TITLE
Add an option to limit the number of rows to read

### ISSUE THREAD

**Issue by zentree** [hadley/readxl#7]
Often users of Excel files add additional information at the top of the page (which can be skipped with current functionality) and following the data we need to read (which I would like to skip too).

**Comment by pommedeterresautee** [comment]
For top information you are not interested in you can use `skip` parameter.

**Comment by Nihasa** [comment]
To get around this, I read the file in using the read_excel() function, and subset it afterwards, getting the sections that you need. It's so fast that doing View(read_excel(yourfile)) and then 
read_excel(yourfile)[firstrow:lastrow,firsttcol:lastcol] works just fine even with pretty large datasets.

**Comment by jennybc** [comment]
I suspect this will be handled by #8, so maybe it can be closed?

**Comment by jennybc** [comment]
Closing. Covered by #8.
