### ISSUE TITLE
Strings with backslashes

### ISSUE THREAD

**Issue by quietlyanalysing** [hadley/readxl#70]
I'm reading in an Excel sheet that has a column of ID numbers like 'S0005497\4'. When this is read into R, I get a double backslash, i.e. 'S0005497\\\4'.

Its probably easy enough to remove one of the backslashes but I thought I'd mention this anyway.

**Comment by hadley** [comment]
Are you sure it's not just printing two backslashes? A reproducible example would be helpful.

**Comment by quietlyanalysing** [comment]
I think its just printing it as when I later write it to a csv, the double backslash becomes one backslash. And also in the viewer, it only shows one backslash.

I only thought this would be an issue as I have to merge to a database using an ID.
