### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mandel01** [hadley/readxl#72]
Re: install.packages("readxl") as described at http://blog.rstudio.org/2015/04/15/readxl-0-1-0/

I tried following the installation instructions but received the error, "package ‘readxl’ is available as a source package but not as a binary". Output from within RStudio is below.

-----

R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Workspace loaded from ~/.RData]

> install.packages("readxl")

   package ‘readxl’ is available as a source package but not as a binary

Warning in install.packages :
  package ‘readxl’ is not available (as a binary package for R version 3.1.3)

**Comment by hadley** [comment]
Looks the mac builder hasn't built it yet - just wait a day or two and try again.
