### ISSUE TITLE
Add an option for recognizing logicals

### ISSUE THREAD

**Issue by kkmann** [hadley/readxl#73]
Hey, I used xlsx so far, which recognizes columns containing only TRUE/FALSE as logical. Would it be possible to include some kind of support for boolean columns (maybe optional)?

**Comment by jeromyanglim** [comment]
I agree. This seems almost like a bug to me. At present readxl appears to import columns with logical values in Excel as 0-1 variables.  If you have a column that contain TRUE/FALSE in Excel, then this should be imported as a character vector in R. 

Just to clarify, I would not call this an "option" as presumably it should be standard behaviour for any R function that imports Excel spreadsheets. In addition to the xlsx package, importing logical excel variables as logical in R is also standard behaviour for the gdata package.

I can imagine users assuming that TRUE/FALSE columns in Excel would be imported as logical in R. 
This would causes issues in subsequent analyses. 

It also sometimes throws the message `Unknown type: 517`.

**Comment by jennybc** [comment]
Covered by #198 

@jeromyanglim If you can provide a reprex of this, please do so and open another issue:

> It also sometimes throws the message `Unknown type: 517`.

**Comment by jennybc** [comment]
This will happen #270.
