### ISSUE TITLE
Downloaded readxl got following error message

### ISSUE THREAD

**Issue by mainwaring** [hadley/readxl#76]
library(readxl)
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘Rcpp’
In addition: Warning message:
package ‘readxl’ was built under R version 3.1.3 
Error: package or namespace load failed for ‘readxl’
> 
I am using the version of R called "Pumpkin Helmet" I tried to run readxl and got the above error message.
Alan

**Comment by hadley** [comment]
Sounds like something went wrong with the install. I'd recommend re-installing.
