### ISSUE TITLE
Non-ascii characters in headers in .xls files not read correctly

### ISSUE THREAD

**Issue by huftis** [hadley/readxl#88]
When the header (the first row) in an .xls file contains non-ASCII characters, it is incorrectly interpreted. For example, an .xls file with this data

    foo   fooæøå   ☃→☺
    bar   bår      test
    baz   æz       ☃→☺

results in the following (on Windows):

    > d = read_excel("h:/non-ascii.xls")
    > d
      foo fooÃ¦Ã¸Ã¥                â˜ƒâ†’â˜º
    1 bar       bår                     test
    2 baz        æz <U+2603><U+2192><U+263A>

That is, the two *data* rows are read correctly, but the header row is mangled. It looks like what happens when you interpret UTF-8 byte sequences as ISO-8859-1 (or Windows-1252).

Note that this only happens with .xls files. The same data saved as an .xlsx file works fine.

    > sessionInfo()
    R version 3.1.1 (2014-07-10)
    Platform: x86_64-w64-mingw32/x64 (64-bit)
    
    locale:
    [1] LC_COLLATE=Norwegian-Nynorsk_Norway.1252  LC_CTYPE=Norwegian-Nynorsk_Norway.1252   
    [3] LC_MONETARY=Norwegian-Nynorsk_Norway.1252 LC_NUMERIC=C                             
    [5] LC_TIME=Norwegian-Nynorsk_Norway.1252    
    
    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base     
    
    other attached packages:
    [1] readxl_0.1.0
    
    loaded via a namespace (and not attached):
    [1] Rcpp_0.11.5 tools_3.1.1

**Comment by hadley** [comment]
Can you please include a link to the xls file?

**Comment by huftis** [comment]
Here’s the .xls file and an equivalent .xlsx file:

http://huftis.org/nedlasting/excel/non-ascii.xls
http://huftis.org/nedlasting/excel/non-ascii.xlsx

I’m now on a Linux system, and have been able to test the files with the latest Git version of `readxl`. It turns out that the result of reading the .xls file depends on the user’s locale. With my default locale, which uses UTF-8, both files work fine. But if I start R with `LC_ALL=C R`, the .xls version has malformed headers. So it looks like the header row is read as being in the character encoding of the user’s locale instead of in the character encoding of the actual file.

**Comment by hadley** [comment]
I couldn't test it, but I'm pretty sure this is the fix needed.
