### ISSUE TITLE
Problem reading in .xls file

### ISSUE THREAD

**Issue by sgermani** [hadley/readxl#92]
I tried this with CRAN version 0.10 and with the development version as of 9/22 and could not read in this  .xls file.

If you try this code:

download.file("https://www.dropbox.com/s/5pny95e6xfom9gu/Hypo_Export.xls?dl=0",
              method = "curl", dest = "returns.xls")
read_excel("returns.xls",skip=4)

I get:

Not an excel file
Error: Failed to open

**Comment by lifan0127** [comment]
I am not able to open your file even in Excel. So I suspect it is not a problem of readxl.

**Comment by hadley** [comment]
I can open it in excel, but the error message is coming from the libxls library. I'll pass it on to the maintainer of libxls.

**Comment by dhoerl** [comment]
You can put whatever file extension you want on a document, but it won't make it a binary 2007 formatted Excel .xls file. If you examine your file, you will find its in the "XML" Excel format, which excel will tag with a .xlsx extension. if you can read the file with 'more' or 'cat', then its not a binary file.

libxls will never support this format, but there are other utilities out there that do - in some ways its much easier as the format is structured XML, not the hodgepodge of binary gunk the old format is.

**Comment by hadley** [comment]
@dhoerl it's not an xlsx either (because that's a zip file containing multiple xml files).  I think it's actually an "excel 2004 XML spreadsheet", with the incorrect extension (should be .xml)

@sgermani I don't have any plans to support this format since it seems to be a transitional format that was only used briefly

**Comment by sgermani** [comment]
Got it.  Thanks for all your help and I love the package Hadley.

**Comment by nks1974** [comment]
Hi Sgermani, a solution to the issue is to re-save the files using excel and then run read_xslx on the new files. A vba macro can be used to run through multiple files and re-save them, eg a loop around "ActiveWorkbook.SaveAs Filename:=strTarget, FileFormat:=51"
