### ISSUE TITLE
External dependencies on Mac OS?

### ISSUE THREAD

**Issue by leeper** [hadley/readxl#97]
So, I received a bug report on rio (https://github.com/leeper/rio/issues/34) related to behavior of importing .xlsx files. In this case, rio uses `read_excel`. I can't reproduce this on Windows, so I suspect it's OS dependent. So, that's as an FYI.

As an actual issue, though, the person who reported that bug [says](https://github.com/leeper/rio/issues/34#issuecomment-100223393) **readxl** depends on XCode, but your DESCRIPTION lists no system dependencies. Is this true?

**Comment by hadley** [comment]
It does not depend on Xcode. If you want to build it locally, you'll obviously need a C/C++ compiler, but most people will install from CRAN.

FWIW I'm pretty sure I fixed that bug in the released version, so it's not an OS issue, it's an issue with using an old version of readxl.
